export const SAFE_PLAYBACK_BOUNDARY_EVENT = "solar:safe-playback-boundary";
export const SERVICE_WORKER_CANDIDATE_READY = "SOLAR_APP_CANDIDATE_READY";
export const SERVICE_WORKER_ACTIVATE_CANDIDATE = "SOLAR_ACTIVATE_CANDIDATE";
export const SERVICE_WORKER_CACHE_RUNTIME_ASSETS = "SOLAR_CACHE_RUNTIME_ASSETS";
export const SERVICE_WORKER_COMMIT_ACTIVE_CACHE = "SOLAR_COMMIT_ACTIVE_CACHE";
